### ISSUE TITLE
Frequency is changed 

### ISSUE THREAD

**Issue by laarhoven1** [RoelKroes/TBTracker-RX#1]
Try via webinterface to change the frequency to 434.700 but ttgo displays still the 434.126 mhz.

**Comment by zanco** [comment]
I can confirm this is happening, but I've changed the frequency to 432.662 (my lora transmitter) , the display shows indeed 434.126 as RX frequency, but as soon as there is a packet received it shows the right frequency. 

![IMG20221219105553](https://user-images.githubusercontent.com/4477734/208398922-fa40ea07-0c3c-4c63-a80b-0f9aa7cca8da.jpg)
I know I have to clean the display ;-)

**Comment by RoelKroes** [comment]
The LCD display shows the last packet received. But I can understand it is confusing if you do not have the web interface open. So, I will change it to show the current RX frequency in the next release.

**Comment by RoelKroes** [comment]
I've implemented this in v0.0.1

When you update the RX frequency from the webinterface, the OLED display will show the new frequency.
