### ISSUE TITLE
GPS update to Sondehub

### ISSUE THREAD

**Issue by GaviG3** [RoelKroes/TBTracker-RX#19]
Hello,
thank you for this great sketch :)

I have just got this running on my Lilygo Tbeam V1.2
I have set my default GPS lat & Lon  with alt.

My GPS pins on the board are stated as 34 and 12 which appears correct in settings.h
The GPS has lock and flashes the RED LED under the Chip.

I show up on Sondehub at my default gps coordinates, but does not update as i move along...
any suggestions?

on the oled, it says chase: and no parameter am I missing a way to enable chase maybe?

Thanking you,
Gavin

**Comment by GaviG3** [comment]
So I left it on yesterday for ages.
My car icon on sondehub stayed at the default coordinates I set.
But if I open google maps from web interface, it showed correct location.

after about an hour, sondehub started working as expected. The car reported accurate location. If I clicked the reset button, and power cycled the unit, it got gps lock instantly….but sondehub car went back to default coordinates and took ages to start reporting correctly again.

Any suggestions?

**Comment by RoelKroes** [comment]
Hi Gavin,

Your position is only uploaded to Sondehub once. You need to reset your ESP32 to get the software to upload your position again. 

Uploading your position takes a couple of seconds and so you might miss some data packets, especially SSDV packets. That is why it was implemented this way.

Do you have a suggestion on how to improve this?

Roel.

**Comment by GaviG3** [comment]
Hi Roel, thank you for getting back to me.

even with resetting, it defaults to the coordinates I manually entered. If I leave it on long(45 to 60 minutes), it seems to use the GPS at random…. 

Maybe if I set lat to 0.000 and long to the same, it may force it to use GPS?

What you say about missing data packets makes sense. I’m all very new to this so I am unable to offer any improvement suggestions but thanks again for your time in making this project.

Gavin

**Comment by RoelKroes** [comment]
I've looked at it. I should be able to change this GPS behaviour for you in the next version. But I will need some time to build that. Thanks for reporting!

**Comment by GaviG3** [comment]
Thank you for the update and making this program :)

**Comment by RoelKroes** [comment]
Hi Gavin,

I've created a new version V0.0.12. This solved the bug you found and added a button to the webinterface to manually upload your position. So it wll be much easier to use the software as a chasing device.

what happens in the software is this:
- the position uploads will happen automatically each 30 minutes 
- you can press the "upload your position" button at any moment to update the Sondehub map with your live position

Would you like to test this version before I will set this live for everybody? I can send you the code by e-mail.

Roel.

**Comment by GaviG3** [comment]
Hi RoelThank you for thisI’d be happy to test it for you, please feel free to email Kind Regards,Gavin ***@***.***+44 (0)750 1190 786Sent from my iPhoneOn 15 May 2024, at 10:53, RoelK ***@***.***> wrote:﻿
Hi Gavin,
I've created a new version V0.0.12. This solved the bug you found and added a button to the webinterface to manually upload your position. So it wll be much easier to use the software as a chasing device.
what happens in the software is this:

the position uploads will happen automatically each 30 minutes
you can press the "upload your position" button at any moment to update the Sondehub map with your live position

Would you like to test this version before I will set this live for everybody? I can send you the code by e-mail.
Roel.

**Comment by RoelKroes** [comment]
Perfect. See attachment. You can copy these files over the old files and use your old settings.h (not included in this zip file).

[TBTracker-RX.zip](https://github.com/RoelKroes/TBTracker-RX/files/15320615/TBTracker-RX.zip)

Let me know if it is working and what you think :-)

Roel.

**Comment by GaviG3** [comment]
Hi Roel,

Thank you for this, it appears to be working :)

I will go give it a full test on the weekend 


Kind Regards,

Gavin Gill

**Comment by GaviG3** [comment]
Seems to be working great, thank you for the update
