### ISSUE TITLE
Oled display additions

### ISSUE THREAD

**Issue by star210** [RoelKroes/TBTracker-RX#4]
Hi Roel

Firstly thankyou for sharing your work. Im using both a modified version of your tracker (a mix of your latest tracker code and code from a few years ago that you had power pins. I use the power pin to shutdown the gps after a fix) and your new Tracker RX. 

I have added code to the telemetry screen which allows more to be viewed. 
Ive also increased the time PACKET RX stays on screen to 1 second. 
It would also be good to add "seconds since last packet" to the telemetry screen.

I would like to beta test / contribute to this code.    star_holden@hotmail.co.uk

Star

**Comment by star210** [comment]
`void displayUpdate()
{
  displayFlash();
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(WHITE);
  display.setCursor(0, 0);
  display.println(WiFi.localIP().toString().c_str());
  display.setCursor(96, 0);
  display.print("#"); display.print(packetCounter);

  display.drawLine(0, 10, 128, 10, WHITE);

  display.setCursor(0, 13);
  display.print(Telemetry.payload_callsign);
  display.setCursor(64, 13);
  display.print(Telemetry.frequency, 3); display.print("MHz");
  display.setCursor(0, 23);
  display.print(Telemetry.alt, 0); display.print("m");
  display.setCursor(64, 23);
  display.print(Telemetry.distance, 1); display.print("Km");
  display.setCursor(112, 23);
  display.print(Telemetry.compass);
  display.setCursor(0, 33);
  display.print(Telemetry.batt, 2); display.print("V");
  display.setCursor(64, 33);
  display.print(Telemetry.rssi); display.print("dBm");
  display.setCursor(0, 43);
  display.print(Telemetry.temp, 1); display.print((char)247); display.print("C");
  display.setCursor(64, 43);
  display.print(Telemetry.sats); display.print("Sats");
  display.setCursor(0, 53);
  display.print(Telemetry.lat, 6); 
  display.setCursor(64, 53);
  display.print(Telemetry.lon, 6); 
  display.display();`

**Comment by star210** [comment]
Ive changed the telemetry page so ive got all the info on the screen including last fix co ordinates so I can manually type into google :)

**Comment by edegraaff** [comment]
> 
Interesting, could you show a screen image? Seems to me a lot of info on the oled screen or do you use a large one? I had some conversation with Roel regarding last tx timer, tt is in the web interface already. The way i planned to use the TBT-RX was hotspot of my phone during travel, and use the webinterface for al special functions,  since for the telemetrie it should be connected to internet.  I like the project, and can't wait to use it in the car or during holidays to track some HAB's 
Regards nl13974, Eelco

**Comment by RoelKroes** [comment]
I like it and I am going to add it in the next version.

But...

I would like to make it even better by creating different modes selectable by the user.
For example 3 modes:
1. "Default Mode" (like it is now in v0.0.7)
2. "I want to know all mode" (what Star created, see picture below)
3. "Chase mode" (large fonts, less info, for when you are in a car and chasing a payload)

Any ideas about that?

Below a picture of what Star created. It is not perfect yet as the bearing misses a character which is wrapped to the next line. Anyway, that is an easy fix.

![oled](https://user-images.githubusercontent.com/58561387/216840807-45e912f3-7d31-4434-a03a-22a467d1b2f1.jpg)

**Comment by star210** [comment]
The seconds since last transmit can replace the IP address on the "All in One" mode. The IP address appears on the first screen at start up just a quick reset cycle will display it if needs be.

Im currently needing the seconds since last transmit as im testing the some Tracker TX code, sometimes it hangs or the GPS doesnt pickup the sats reliably after a sleep. It lets me know if its working at a glance without waiting for the PACKET RX splash screen.

Good spot with the heading overflow!

**Comment by star210** [comment]
Since we are using the T Beam what about a push of the middle button to switch between "All in One" and "Chase" its GPIO38 ?

**Comment by edegraaff** [comment]
> I like it and I am going to add it in the next version.
> 
> But...
> 
> I would like to make it even better by creating different modes selectable by the user. For example 3 modes:
> 
> 1. "Default Mode" (like it is now in v0.0.7)
> 2. "I want to know all mode" (what Star created, see picture below)
> 3. "Chase mode" (large fonts, less info, for when you are in a car and chasing a payload)
> 
> Any ideas about that?
> 
> Below a picture of what Star created. It is not perfect yet as the bearing misses a character which is wrapped to the next line. Anyway, that is an easy fix.
> 
> ![oled](https://user-images.githubusercontent.com/58561387/216840807-45e912f3-7d31-4434-a03a-22a467d1b2f1.jpg)
Seems it all fits, great, it is maximum info on this small screen. 
Last packet timer is the #27 right up? I could imagine the last received packet is important when you chase, and also the last known coordinates... Did you know meshtastic uses a arrow to point possition? 
![image](https://user-images.githubusercontent.com/12442749/216845037-93cf60b7-26bb-4ba6-8982-d44b70456479.png)

**Comment by star210** [comment]
I didnt know it had an arrow! Is that a compass because a live heading would need the gps to be moving to get a heading. 
The GPS position error while standing still could move the arrow in the wrong direction?

**Comment by edegraaff** [comment]
> I didnt know it had an arrow! Is that a compass because a live heading would need the gps to be moving to get a heading. The GPS position error while standing still could move the arrow in the wrong direction?
Meshtastic makes use of the gps coordinates when availible, how they manage i have no clue, but it is possible to see distance from your mesh node to the other you have a connection with. Als the signal strengt, you can setup the screen to flip every x seconds the next screen. There are 3 screens you can select with pusbutton, or make them flip over x sec.

**Comment by star210** [comment]
Ive added time since last packet to the screen instead of the IP address. 
I moved the heading next to the satellites as there's room.
Add this line to the Telemetry struct:
`  unsigned long lastmillis=0;   // Time in second ssince previous packet was received by the radio`
And this line to Radio
`      Telemetry.lastmillis = millis() - Telemetry.atmillis;`
Just above:
`      Telemetry.atmillis = millis();`

And finally the new screen:
`displayFlash();
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(WHITE);
  display.setCursor(0, 0);
  display.print(Telemetry.lastmillis/1000); display.print("s"); 
  display.setCursor(94, 0);
  display.print("#"); display.print(packetCounter);

  display.drawLine(0, 10, 128, 10, WHITE);

  display.setCursor(0, 13);
  display.print(Telemetry.payload_callsign);
  display.setCursor(64, 13);
  display.print(Telemetry.frequency, 3); display.print("MHz");
  display.setCursor(0, 23);
  display.print(Telemetry.alt, 0); display.print("m");
  display.setCursor(64, 23);
  display.print(Telemetry.distance, 1); display.print("Km");
  display.setCursor(0, 33);
  display.print(Telemetry.batt, 2); display.print("V");
  display.setCursor(64, 33);
  display.print(Telemetry.rssi); display.print("dBm");
  display.setCursor(0, 43);
  display.print(Telemetry.temp, 1); display.print((char)247); display.print("C");
  display.setCursor(64, 43);
  display.print(Telemetry.sats); display.print("Sat");
  display.setCursor(104, 43);
  display.print(Telemetry.compass);
  display.setCursor(0, 53);
  display.print(Telemetry.lat, 6); 
  display.setCursor(64, 53);
  display.print(Telemetry.lon, 6); 
  display.display();`

**Comment by star210** [comment]
Sorry ignore my hack above...ive just found the getduration() function 0_0

**Comment by RoelKroes** [comment]
Thanks guys! I appreciate all this input. 
Let me chew on it and I will implement this in the next realase.

Still a few remarks:

- About the arrow on the screen of the T-Beam. It always points to a position relative to North as the T-Beam has no compass. So I think I can build that. Good idea.

- Using the button on the T-Beam is not a good idea as many people use the software on generic ESP32's which have no standard button

- In Star's example, it is probalby better to replace RSSI with the signal strength.

Thanks,

Roel.

**Comment by ON2ON-HAM** [comment]
Reading all the above, and also testing with V 0.0.7, I would like to say, that the 'Flash' function as it is when a new packet arrives, is great,, A larger Font for the ID/Callsing in a pop-up just after would be nice, and if using a TTGO, the middle button for  a function to recall the last Callsing in a large font.

73 and keep up this great work !

Luke 
ON2ON

**Comment by RoelKroes** [comment]
I implemented three different OLED modes based on this discussion in v0.0.8, which is now live. Also added a "Flash" pin which will be set high for a short moment when a new packet is received.
