### ISSUE TITLE
LoRa Autotune

### ISSUE THREAD

**Issue by KevWal** [RoelKroes/TBTracker-RX#5]
Firstly Thank you Roel, a fantastic product, so useful, and really nicely written :)

A proposed useful enhancement would be to add Autotune,  taking the FrequencyError from the last successful packet and re-tuning by the frequency error?

An example from Dave here https://github.com/PiInTheSky/lora-gateway/blob/master/gateway.c#L1853

Cheers
Kev

**Comment by RoelKroes** [comment]
Hi Kevin,

Thanks for the compliment!
Autotune is very useful indeed. Good thing is, that it is already in the software as of v.0.0.4 :-)

R.

**Comment by KevWal** [comment]
Oops, I see it in the Change log now, I just didn't see it in the config screen :)

20-JAN-2023: Added autotune to the radio (based on the frquency error calculated by the radio)
