### ISSUE TITLE
SSDV Packet Upload

### ISSUE THREAD

**Issue by KevWal** [RoelKroes/TBTracker-RX#6]
Another proposed useful enhancement - hope you don't mind me adding these ideas, would be to add SSDV packet upload?

An example from Dave detecting it is SSDV here:  https://github.com/PiInTheSky/lora-gateway/blob/master/gateway.c#L1737  and then uploading it here:  https://github.com/PiInTheSky/lora-gateway/blob/master/ssdv.c#L52

Cheers
Kev

**Comment by RoelKroes** [comment]
Yes, that would be great and should be in there. 
But at the moment I have no hardware to test it. 
Thanks Kev.

**Comment by KevWal** [comment]
![20230218_130314](https://user-images.githubusercontent.com/2286500/219867398-fb0ca20a-21e5-454e-a123-7650fc0a7bd7.jpg)

If you have time to look at the code I'll make one up and send it to you, no problem.  I have several spare esp32 camera boards, so will only cost me a gps and a radio module...

https://github.com/KevWal/ESP32-Cam-Pico-Project

Cheers
Kev

**Comment by RoelKroes** [comment]
That would be a super idea. 
I will of course send it back to you when I get the software working.

R.

**Comment by KevWal** [comment]
Let me have your address in a private message and I will sort in the next couple of weeks.  No need to send it back, fly it if you can, or keep it for future testing :)

**Comment by RoelKroes** [comment]
Sent you an e-mail 😀
